// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: proto/persona.proto

package persona

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Persona struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Apellido string `protobuf:"bytes,2,opt,name=apellido,proto3" json:"apellido,omitempty"`
}

func (x *Persona) Reset() {
	*x = Persona{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Persona) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persona) ProtoMessage() {}

func (x *Persona) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persona.ProtoReflect.Descriptor instead.
func (*Persona) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{0}
}

func (x *Persona) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Persona) GetApellido() string {
	if x != nil {
		return x.Apellido
	}
	return ""
}

type SubirPersonaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	Estado  string   `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *SubirPersonaReq) Reset() {
	*x = SubirPersonaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubirPersonaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubirPersonaReq) ProtoMessage() {}

func (x *SubirPersonaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubirPersonaReq.ProtoReflect.Descriptor instead.
func (*SubirPersonaReq) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{1}
}

func (x *SubirPersonaReq) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

func (x *SubirPersonaReq) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type SubirPersonaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubirPersonaRes) Reset() {
	*x = SubirPersonaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubirPersonaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubirPersonaRes) ProtoMessage() {}

func (x *SubirPersonaRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubirPersonaRes.ProtoReflect.Descriptor instead.
func (*SubirPersonaRes) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{2}
}

type GuardarPersonaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Persona *Persona `protobuf:"bytes,2,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *GuardarPersonaReq) Reset() {
	*x = GuardarPersonaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuardarPersonaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardarPersonaReq) ProtoMessage() {}

func (x *GuardarPersonaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardarPersonaReq.ProtoReflect.Descriptor instead.
func (*GuardarPersonaReq) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{3}
}

func (x *GuardarPersonaReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuardarPersonaReq) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type GuardarPersonaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuardarPersonaRes) Reset() {
	*x = GuardarPersonaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuardarPersonaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardarPersonaRes) ProtoMessage() {}

func (x *GuardarPersonaRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardarPersonaRes.ProtoReflect.Descriptor instead.
func (*GuardarPersonaRes) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{4}
}

type BajarPersonaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *BajarPersonaReq) Reset() {
	*x = BajarPersonaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BajarPersonaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BajarPersonaReq) ProtoMessage() {}

func (x *BajarPersonaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BajarPersonaReq.ProtoReflect.Descriptor instead.
func (*BajarPersonaReq) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{5}
}

func (x *BajarPersonaReq) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type BajarPersonaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona []*Persona `protobuf:"bytes,1,rep,name=persona,proto3" json:"persona,omitempty"`
}

func (x *BajarPersonaRes) Reset() {
	*x = BajarPersonaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BajarPersonaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BajarPersonaRes) ProtoMessage() {}

func (x *BajarPersonaRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BajarPersonaRes.ProtoReflect.Descriptor instead.
func (*BajarPersonaRes) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{6}
}

func (x *BajarPersonaRes) GetPersona() []*Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type ObtenerPersonaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ObtenerPersonaReq) Reset() {
	*x = ObtenerPersonaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObtenerPersonaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerPersonaReq) ProtoMessage() {}

func (x *ObtenerPersonaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerPersonaReq.ProtoReflect.Descriptor instead.
func (*ObtenerPersonaReq) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{7}
}

func (x *ObtenerPersonaReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ObtenerPersonaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *ObtenerPersonaRes) Reset() {
	*x = ObtenerPersonaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_persona_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObtenerPersonaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerPersonaRes) ProtoMessage() {}

func (x *ObtenerPersonaRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerPersonaRes.ProtoReflect.Descriptor instead.
func (*ObtenerPersonaRes) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{8}
}

func (x *ObtenerPersonaRes) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

var File_proto_persona_proto protoreflect.FileDescriptor

var file_proto_persona_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3d, 0x0a, 0x07, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x22, 0x52, 0x0a, 0x0f, 0x53, 0x75,
	0x62, 0x69, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a,
	0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x11,
	0x0a, 0x0f, 0x53, 0x75, 0x62, 0x69, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65,
	0x73, 0x22, 0x4c, 0x0a, 0x11, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x22,
	0x13, 0x0a, 0x11, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x52, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x42, 0x61, 0x6a, 0x61, 0x72, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x3a, 0x0a, 0x0f, 0x42, 0x61, 0x6a, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52,
	0x65, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x22, 0x23, 0x0a, 0x11, 0x4f,
	0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3c, 0x0a, 0x11, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x32, 0xfc,
	0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x35, 0x0a, 0x05, 0x53, 0x75, 0x62, 0x69, 0x72, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x75, 0x62, 0x69, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x69, 0x72, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x07, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x61, 0x72, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x75, 0x61, 0x72, 0x64,
	0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x05, 0x42, 0x61, 0x6a, 0x61, 0x72, 0x12, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x61, 0x6a, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x61, 0x6a,
	0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x07,
	0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x61,
	0x68, 0x61, 0x77, 0x6b, 0x33, 0x36, 0x30, 0x2f, 0x6c, 0x61, 0x62, 0x32, 0x73, 0x64, 0x2f, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_persona_proto_rawDescOnce sync.Once
	file_proto_persona_proto_rawDescData = file_proto_persona_proto_rawDesc
)

func file_proto_persona_proto_rawDescGZIP() []byte {
	file_proto_persona_proto_rawDescOnce.Do(func() {
		file_proto_persona_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_persona_proto_rawDescData)
	})
	return file_proto_persona_proto_rawDescData
}

var file_proto_persona_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_persona_proto_goTypes = []interface{}{
	(*Persona)(nil),           // 0: grpc.Persona
	(*SubirPersonaReq)(nil),   // 1: grpc.SubirPersonaReq
	(*SubirPersonaRes)(nil),   // 2: grpc.SubirPersonaRes
	(*GuardarPersonaReq)(nil), // 3: grpc.GuardarPersonaReq
	(*GuardarPersonaRes)(nil), // 4: grpc.GuardarPersonaRes
	(*BajarPersonaReq)(nil),   // 5: grpc.BajarPersonaReq
	(*BajarPersonaRes)(nil),   // 6: grpc.BajarPersonaRes
	(*ObtenerPersonaReq)(nil), // 7: grpc.ObtenerPersonaReq
	(*ObtenerPersonaRes)(nil), // 8: grpc.ObtenerPersonaRes
}
var file_proto_persona_proto_depIdxs = []int32{
	0, // 0: grpc.SubirPersonaReq.persona:type_name -> grpc.Persona
	0, // 1: grpc.GuardarPersonaReq.persona:type_name -> grpc.Persona
	0, // 2: grpc.BajarPersonaRes.persona:type_name -> grpc.Persona
	0, // 3: grpc.ObtenerPersonaRes.persona:type_name -> grpc.Persona
	1, // 4: grpc.PersonaService.Subir:input_type -> grpc.SubirPersonaReq
	3, // 5: grpc.PersonaService.Guardar:input_type -> grpc.GuardarPersonaReq
	5, // 6: grpc.PersonaService.Bajar:input_type -> grpc.BajarPersonaReq
	7, // 7: grpc.PersonaService.Obtener:input_type -> grpc.ObtenerPersonaReq
	2, // 8: grpc.PersonaService.Subir:output_type -> grpc.SubirPersonaRes
	4, // 9: grpc.PersonaService.Guardar:output_type -> grpc.GuardarPersonaRes
	6, // 10: grpc.PersonaService.Bajar:output_type -> grpc.BajarPersonaRes
	8, // 11: grpc.PersonaService.Obtener:output_type -> grpc.ObtenerPersonaRes
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_persona_proto_init() }
func file_proto_persona_proto_init() {
	if File_proto_persona_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_persona_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Persona); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubirPersonaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubirPersonaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuardarPersonaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuardarPersonaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BajarPersonaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BajarPersonaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObtenerPersonaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_persona_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObtenerPersonaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_persona_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_persona_proto_goTypes,
		DependencyIndexes: file_proto_persona_proto_depIdxs,
		MessageInfos:      file_proto_persona_proto_msgTypes,
	}.Build()
	File_proto_persona_proto = out.File
	file_proto_persona_proto_rawDesc = nil
	file_proto_persona_proto_goTypes = nil
	file_proto_persona_proto_depIdxs = nil
}
